MDScreen:
    name: "Chip"
    MDBoxLayout:
        orientation: "vertical"
        MDLabel:
            text: "Voici un MDChip avec du texte :"
            halign: "center"
        MDChip:
            text: "Exemple de MDChip"
            pos_hint: {"center_x": 0.5, "center_y":.4}
            text_color: 'blue'
            font_size: 20
            size_hint: .2, None
            md_bg_color: 'red'
